package com.barclay.tenziapi.models

enum class SecurityRoles(val roleName: String) {
    STUDYGUIDE_CREATE("STUDYGUIDE_CREATE"),
    STUDYGUIDE_READ("STUDYGUIDE_READ"),
    STUDYGUIDE_UPDATE("STUDYGUIDE_UPDATE"),
    STUDYGUIDE_DELETE("STUDYGUIDE_DELETE"),
    TERM_CREATE("TERM_CREATE"),
    TERM_READ("TERM_READ"),
    TERM_UPDATE("TERM_UPDATE"),
    TERM_DELETE("TERM_DELETE"),
    DEFINITION_CREATE("DEFINITION_CREATE"),
    DEFINITION_READ("DEFINITION_READ"),
    DEFINITION_UPDATE("DEFINITION_UPDATE"),
    DEFINITION_DELETE("DEFINITION_DELETE"),
}